### ISSUE TITLE
Extraction of token not well explained

### ISSUE THREAD

**Issue by laurence702** [Sambego/nestjs-auth0-api#1]
Hello Auth0, I checked this codebase and also the [tutorial](https://www.youtube.com/watch?v=JzndSOAb6SQ&list=TLPQMjAwOTIwMjGVwhVTrYPyUA&index=1&ab_channel=Auth0) that this arises from, and just want to point out that the process to get the auth token isn't well explained. I'd like a pointer in the docs or the video explained better as I want to explore using Auth0 for future apps, I've used a couple of options in the past which though worked fine, i want to explore something new(Auth0)

**Comment by Sambego** [comment]
Hey @laurence702, the NestJS video tutorial and this codebase do not talk about obtaining a token, but only on how to validate Auth0 Access Tokens to protect API endpoints.

If you'd like some more information on how to get an Access Token, you can follow one of our many [quickstarts](https://auth0.com/docs/quickstart/spa) or check one of other videos like [this](https://www.youtube.com/watch?v=egnVe9lXY0E) or [this](https://www.youtube.com/watch?v=aRBgA8N0ioM) one!
